[package]
name = "t3zktls-core"
version.workspace = true
edition.workspace = true

[dependencies]
t3zktls-program-core = { workspace = true }

log = { workspace = true }

anyhow = { workspace = true }

alloy = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
